### ISSUE TITLE
Installing from setup.py is deprecated

### ISSUE THREAD

**Issue by guigoruiz1** [Mayitzin/ahrs#104]
`DEPRECATION: Loading egg at /opt/conda/lib/python3.11/site-packages/AHRS-0.3.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330`

The package version available via pip installation does not have all the features in the documentation which I need for my project. Would it be possible to bring the pip version up to date?

Thank you

**Comment by Mayitzin** [comment]
The setup method was updated with commit dfc37b8ce232addd7965c38a883d70998e4a9804

Now it uses a `pyproject.toml` configuration file.
