### ISSUE TITLE
Need pre-recorded data to test the AHRS library's Extended Kalman Filter

### ISSUE THREAD

**Issue by amanabt** [Mayitzin/ahrs#114]
Friends,

I am just getting started with a project where I have to implement an Extended Kalman Filter (EKF) based on the EKF implementation of this library. This is the first time I am venturing into this field and need some help getting started.

At first I wanted to get a feel of how the your implementation of your EKF is used. Unfortunately, I do not have a primary source (hardware) of getting the gyroscope, accelerometer, and magnetometer data.

Could you please suggest me some pre-recorded data that I could use to test this library? I need 3 axis gyroscope, 3D accelerometer, and a magnetometer data.

**Comment by Mayitzin** [comment]
Hi, @amanabt 

In the discussions post of [Datasets](https://github.com/Mayitzin/ahrs/discussions/20) you can find a couple that are good to test the different algorithms, including the EKF.

Cheers!

**Comment by Mayitzin** [comment]
No further comments were added. I think we can close this issue.
