### ISSUE TITLE
Is the platform assumed to be stationary (acceleration =0) for the EKF ? 

### ISSUE THREAD

**Issue by surajbijjahalli** [Mayitzin/ahrs#119]
Hello, thank you for this great library. 
For the EKF update with the accelerometer, is it assumed that the platform is at rest or at constant velocity ? 
Otherwise the tilt estimation would no longer be valid. Am i correct ?

**Comment by Mayitzin** [comment]
Hi! That's correct.

It is assumed that the sensed acceleration is around 1g (~9.81 m/s^2), which is ideal to compare it against the normal gravitational vector.

If the sensor is moving, it will add external accelerations deviating the measurements towards 0g (free fall) or greater than 1g (irregular high intensity accelerations.)

When those accelerations alter the expected 1g, they will degrade the estimation.

It is, thus, recommended to identify the limits, and uses of your algorithm. If those accelerations come often, then give it a bigger uncertainty.

If they are not common, you can trust the accelerometer and give it a smaller uncertainty.

**Comment by surajbijjahalli** [comment]
Many thanks for your answer and help!
