### ISSUE TITLE
fix import problem

### ISSUE THREAD

**Issue by orekides** [Mayitzin/ahrs#18]
the **am2q** function is used in the  **ekf.py** file , but not imported
`Q[0] = am2q(self.acc[0], self.mag[0]) if self.q0 is None else self.q0/np.linalg.norm(self.q0)`  in ekf.py line 77.

**Comment by Mayitzin** [comment]
Thanks. The import is fixed now with commit e1725267b0009a8a573f99dbf8d06e8481407ab6 .

It will now use the new function `ecompass` instead of the old `am2q`. Eventually, `am2q` will be removed in favour of the new function.
