### ISSUE TITLE
Class constructor with data not working

### ISSUE THREAD

**Issue by perotom** [Mayitzin/ahrs#21]
I tried to get this simple code working but it seems like the constructor is not working correctly:

```
print(data[GYR].shape)
print(data[ACC].shape)
print(data[MAG].shape)
madgwick = Madgwick(gyr=data[GYR],
                        acc=data[ACC], 
                        mag=data[MAG], 
                        frequency=200)
print(madgwick.Q)
```

will output:

```
(11995, 3)
(11995, 3)
(11995, 3)
AttributeError: 'Madgwick' object has no attribute 'Q'
```

Assumption: In the constructor `self.input = args[0] if args else None` will always be `None` as args is always empty with named parameters?

**Comment by Mayitzin** [comment]
Which version are you using?

**Comment by perotom** [comment]
Yesterday I did the installation which resulted in: Version: 0.2.2 with Python 3.8.2

**Comment by orekides** [comment]
the pypi version is too old, you should install the latest version by following the **readme**

**Comment by perotom** [comment]
Ok thanks.
To avoid this it would be better suited for people using pip: `pip install git+https://github.com/Mayitzin/ahrs.git`.
