### ISSUE TITLE
Unit of acc, gyr and magnetometer in ExampleData.mat

### ISSUE THREAD

**Issue by golly10** [Mayitzin/ahrs#23]
Hi!, I'm trying to run your program to observe how the IMU filter works, but I can't understand the example data file. I thought the acceleration should be between [-9.8, 9.8], but the data seems to be in the range [-1, 1], what measure unit are you using for the accelerometer, gyroscope and magnetometer? Maybe, this data is in gForce (gravity removed) instead of m/s^2 and that's why it is in that range, but I want to be sure and check it with the author. 

Thanks in advance.

**Comment by Mayitzin** [comment]
Hi, the recording `ExampleData.mat` is in [G units](https://en.wikipedia.org/wiki/G-force). Many algorithms normalize the acceleration measurements to easily estimate and compute the attitude especially in static poses, including the well-know Madgwick algorithm, from which the sample data comes from. I hope this helps you.
