### ISSUE TITLE
syntax error in geometry

### ISSUE THREAD

**Issue by anisghaoui** [Mayitzin/ahrs#28]
Hi,
you might want to remove the second `:` in the parameters
https://github.com/Mayitzin/ahrs/blob/ad265e37acad945f13fb131e6cf71b63b3c76a76/ahrs/common/geometry.py#L40

Thanks <3.

**Comment by Mayitzin** [comment]
Thanks for the heads up! Fixed with commit 9fb0e19b9e5eabca289d19c1a312ba13ff6e5c59
