### ISSUE TITLE
CSV file delimiter

### ISSUE THREAD

**Issue by AlmoniPloni** [Mayitzin/ahrs#3]
support ',' (coma) when reading CSV file

**Comment by Mayitzin** [comment]
Branch: development
Commit: [2a0d5d4](https://github.com/Mayitzin/ahrs/commit/2a0d5d4196b3828af5befcf5ac90d1b54cb13d2c)

New definition of function `ahrs.utils.load(file_name, separator=';')` now includes the parameter `separator` to specify a desired character used to split the data.

It will be merged to master in release 0.2.3.

**Comment by AlmoniPloni** [comment]
Thank you.
