### ISSUE TITLE
Unable to use TRIAD filter -  TypeError

### ISSUE THREAD

**Issue by rajesh0therascal** [Mayitzin/ahrs#39]
Following error was observed

`\env\lib\site-packages\ahrs\filters\triad.py line 379, in _compute_all
    num_samples = len(self.w1)
TypeError: len() of unsized object`

while executing the code

```python
import numpy as np
from ahrs.filters import TRIAD
triad = TRIAD()
triad.v1 = np.array([0.0, 0.0, 1.0])                    # Reference gravity vector (g)
triad.v2 = np.array([21.0097, 1.3335, 43.732])          # Reference geomagnetic field (h)
a = np.array([-2.499e-04, 4.739e-02, 0.9988763])        # Measured acceleration (normalized)
a /= np.linalg.norm(a)
m = np.array([-0.36663061, 0.17598138, -0.91357132])    # Measured magnetic field (normalized)
m /= np.linalg.norm(m)
triad.estimate(w1=a, w2=m)
```
Python version 3.7.4
Numpy 1.21.0
Windows 10 - 64 bit

**Comment by Mayitzin** [comment]
Thanks for pointing this out. The error was at the construction of the object. I was trying to detect empty arrays the wrong way. I changed it to a more robust method using ``all([self.w1, self.w2])`` with commit ea592407be423ed4afcb292acf925d742203ed40

If it keeps giving you trouble let me know.
