### ISSUE TITLE
Error in Munich information?

### ISSUE THREAD

**Issue by ogreyesp** [Mayitzin/ahrs#42]
Hi

First of all, thanks for this amazing and helpful library.

In EKF filter, you are using the Munich information in case the magnetic reference is not provided. You are constructing a magnetic model as follows

![image](https://user-images.githubusercontent.com/17004570/125046282-28450a80-e09e-11eb-85af-6bf13ce2c518.png)

 However, according to the WMM class, the height should be in kilometres, but you have defined the MUNICH_HEIGHT in meters.

![image](https://user-images.githubusercontent.com/17004570/125046457-5296c800-e09e-11eb-8659-647c5e6bc9db.png)

Is it a bug?

Best regards

**Comment by Mayitzin** [comment]
Hi! You're right. The height was wrongly represented in km. It should be ``0.519``. It was corrected with the commit 462d81f35125abddf129ca850dedb17ac8a2b5fa

Thanks for pointing that out.
