### ISSUE TITLE
class AngularRate does not accept q0

### ISSUE THREAD

**Issue by l82ky** [Mayitzin/ahrs#49]
https://github.com/Mayitzin/ahrs/blob/master/ahrs/filters/angular.py#L355

q0 argument is ignored by the AngularRate constructor

In __init__ declaration q0 is specified as a named argument:
>    def __init__(self, gyr: np.ndarray = None, q0: np.ndarray = None, frequency: float = 100.0, order: int = 1, **kw):

But self.q0 is set via **kw:
>            self.q0 = kw.get('q0', np.array([1.0, 0.0, 0.0, 0.0]))

**Comment by Mayitzin** [comment]
Fixed in commit dd914a209fe82875873689624596025759a5f8fd
