### ISSUE TITLE
MUNICH_HEIGHT is still in meters in PIP package

### ISSUE THREAD

**Issue by ogreyesp** [Mayitzin/ahrs#52]
Hi

The MUNICH_HEIGHT error (it was in meters) was corrected in GitHub, but it is still present if you install the last version of the package from PIP.

Could you release a new version of the package?

Best regards

**Comment by Mayitzin** [comment]
A new release (v0.3.1) has been uploaded to [pypi](https://pypi.org/project/AHRS/). You can now update the package with pip. Alternatively, the distribution packages can be found in the [releases](https://github.com/Mayitzin/ahrs/releases) page.
