### ISSUE TITLE
provided Q0 in AngularRate filter is not respected

### ISSUE THREAD

**Issue by mcm001** [Mayitzin/ahrs#56]
https://github.com/Mayitzin/ahrs/blob/master/ahrs/filters/angular.py#L360

q0 is given as part of the named arguments, but it's only initialized from kwargs.

**Comment by mcm001** [comment]
Duplicate of #49

**Comment by Mayitzin** [comment]
Fixed in commit dd914a209fe82875873689624596025759a5f8fd
