### ISSUE TITLE
Mag data unit inconsistency in documentation

### ISSUE THREAD

**Issue by dawnclaude** [Mayitzin/ahrs#68]
According to the documentation, the EKF class constructor takes mag_data in mT units, but the update function takes mag_data in uT units.

**Comment by Mayitzin** [comment]
Thanks. Both were actually wrong. Some manufacturers use uT, and some others mT, but the geomagnetic data is normally handled as nT by the National Agencies.

Fixed with commit a4e225b26a58da30a7bd5892a7447cccdd7c8a29
