### ISSUE TITLE
Yaw initial angle question

### ISSUE THREAD

**Issue by Jason-Dellai** [Mayitzin/ahrs#69]
Hello,

I am currently doing an internship in a research laboratory. I would like to use IMU to know the orientation of the hand.

I am currently having problems with the yaw angle. Depending on the algorithm I use I have a different yaw angle at the beginning of my recording (+150° with Madgwick and Fourati // -50° with Complementary filter). I would like to know if it is possible to reset the orientation at the beginning of my recording in order to have a zero yaw, roll and pitch. This will allow me to express the orientation of the hand with respect to an initial reference orientation. 

![image](https://user-images.githubusercontent.com/72765356/161554403-9122892e-2b4d-400c-81ff-672c9d9321c8.png)

![image](https://user-images.githubusercontent.com/72765356/161554274-52282e90-2629-4cc8-bcf1-b6a2af1494f4.png)

![image](https://user-images.githubusercontent.com/72765356/161559523-6f577b19-e04f-4bf6-87d3-226ed3f9f1d7.png)

I also have a question about the function
 ahrs.utils.metrics.qad
what is the unit of the angular deviation obtained?

**Comment by Mayitzin** [comment]
Hi, may I as which version of AHRS do you use? Recenty there have been small changes, and the initial values of some algorithms are among those changes.

And regarding the `qad` function: It is unitless. Each value of a Quaternion has no unit, and the QAD simply tells us how different among each other are these unitless values.
