### ISSUE TITLE
Unexpected result for attitude estimation

### ISSUE THREAD

**Issue by Marina-Andric** [Mayitzin/ahrs#9]
Hi, 
I have been experimenting with the ahrs module. First I used example sensor data (ExampleData.mat) and some of the code from https://pypi.org/project/AHRS/ to obtain Euler angles and then compared them with the output from the [MATLAB implementation](https://x-io.co.uk/open-source-imu-and-ahrs-algorithms/) of Madgwick algorithm. The resulting two plots of Euler angles for the same dataset look surprisingly different.
![ahrs_python](https://user-images.githubusercontent.com/16718215/95000152-ada30800-05be-11eb-8303-1e5e4e05bc15.png)
![euler_angles_matlab](https://user-images.githubusercontent.com/16718215/95000153-af6ccb80-05be-11eb-9db9-f5b0c5b2a727.png)

Quaternions were computed using this code:

    madgwick = ahrs.filters.Madgwick()
    Q = np.tile([1., 0., 0., 0.], (data.num_samples, 1))
    d2g = ahrs.common.DEG2RAD
    for t in range(1, data.num_samples):
       Q[t] = madgwick.updateMARG(Q[t-1], d2g*data.gyr[t], data.acc[t], data.mag[t])

and then the Euler angles were then obtained from them using the transformation function from the [quaternions](https://github.com/mjsobrep/quaternions) module.
Have I made some mistake?
Thanks,
Marina

**Comment by Mayitzin** [comment]
The example file used by Madgwick was sampled at 256 Hz. All estimators of this package have a default sampling frequency of 100 Hz, so you must especify the required frequency in the creation of the class:

```python
madgwick = ahrs.filters.Madgwick(frequency=256.0)
```

I also recommend to try the newest version of the package, which has a better documentation and is easier to use. For this example (Madgwick also sets beta to 0.1) you simply do:

```python
>>> madgwick = Madgwick(gyr=gyro*DEG2RAD, acc=accs, mag=mags, frequency=256.0, beta=0.1, q0=[1.0, 0.0, 0.0, 0.0])
```

By giving the data, it will automatically compute all the values and the computed quaternions will be stored in the attribute `Q`:

```python
>>> madgwick.Q.shape
(6959, 4)
```

This new version is available, for now, only by cloning the repository from github. I'm working to finish some details and put it on pypi as soon as possible.
