### ISSUE TITLE
Isn't it required to normalize quaternion estimation in EKF?

### ISSUE THREAD

**Issue by PeterBorisenko** [Mayitzin/ahrs#96]
Just after we integrate quaternion using angular rates it's norm is not necessary equals to 1.
So it's illegal to use this estimation as attitude representation and DCM based on it will also be incorrect. 

Please explain if I am wrong.

**Comment by Mayitzin** [comment]
The integration of the quaternion is done with the linearized Taylor series, which actually yields a normalized quaternion, as explained in the documentation of the estimator "Attitude from Angular rate" https://ahrs.readthedocs.io/en/latest/filters/angular.html#quaternion-integration

Mathematically, it is not necessary to normalize it. However, you're right, it wouldn't hurt to add an extra normalization line at the end of the method ``f`` of the EKF. I'll add it.

**Comment by PeterBorisenko** [comment]
Yeah after I have checked the values it actually doesn't not look that bad. It gives about 0.7e-8 error on my test data so the result won't be affected in any noticeable way.
