### ISSUE TITLE
EKF update Qt

### ISSUE THREAD

**Issue by tkumpumak** [Mayitzin/ahrs#97]
In the EKF update function where do this another 0.5*dt come from? I don't see it in the equations on the documentation.

W   = 0.5*dt * np.r_[[-q[1:]], q[0]*np.identity(3) + skew(q[1:])]  # Jacobian W = df/dω
Q_t = 0.5*dt * self.g_noise * W@W.T     # Process Noise Covariance

**Comment by Mayitzin** [comment]
Omg! You're right. That 0.5*dt shouldn't be there. I fixed it with the commit a214a7b33762e510ea64b19edec40a370078718c

It doesn't change much of the result, but it has to be correct.

Thanks for pointing it out!
